load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "resourcepool",
    srcs = [
        "parse.go",
        "pool.go",
    ],
    importpath = "github.com/buildbarn/bb-remote-execution/pkg/resourcepool",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/proto/configuration/bb_worker",
    ],
)
